#+TITLE: Calendar and Material
#+AUTHOR:
#+DATE: <2020-08-30 Sun>
#+STARTUP: showall

The course runs from Sep, 14, 2020 till Dec 15, 2020 with the
following schedule:

- Mondays, 14:30-16:00
- Tuesdays, 9:00-10:30

The Zoom link for the video conference available on the Moodle
platform at the University of Trento.

#+BEGIN_warning
Interactive sessions are recorded and made available on the Internet
for reference and support to other students.  If you do not wish to be
recorded, you can organize a meeting with one of the professors.
#+END_warning

You might want to read the [[file:./instructions.org][Instructions]] to understand how to take the
course.  (And the expression "you might want ..." gets translated in
Italian with: "è assolutamente necessario che ...".)

Notice also the titles and structure of the lessons yet to be
delivered might change slightly .  The rule of the thumb is: if there
are links with materials, things won't change; if there are no links
to the materials, titles and content are just suggestions.

#+begin_src ruby :exports results :results html output :var lesson_plan = lesson-plan
  def content_to_string content_type, content
    if content_type == "Q&A"
       "Q&A about lessons #{content}."
    elsif content_type == "Prepare"
       "Students prepare L#{content}"
    else
       content
    end
  end

  def link_if file, name, options = {}
    (file and File.exists?(file)) ? "<a href=\"#{file}\" #{"download" if options[:download]}>#{name}</a>" : name
  end

  def lesson_to_materials lesson_number, materials
    mats = materials.select { |x| lesson_number == x[:lesson] and x[:topic_number] != "Z" and x[:topic_number] != "ZX" }
    mats.map { |x|
      "#{x[:basename]} (#{link_if(x[:video], "VIDEO")}) (#{link_if(x[:pdf], "PDF")})"
    }.join("<br/>\n")
  end

  def zoom_lesson_to_materials lesson_number, materials
    mats = materials.select { |x| lesson_number == x[:lesson] and (x[:topic_number] == "Z" or x[:topic_number] == "ZX") }
    mats.map { |x|
      "#{x[:basename]} (#{link_if(x[:pdf], "PDF")})"
    }.join("<br/>\n")
  end

  # take a filename in the "material" directory and break it into its basic components
  # (the most important of which being the lesson number)
  def filename_to_elements filename
    elements = File.basename(filename).split "."

    hash = {}
    hash[:pdf] = filename
    hash[:basename] = File.basename filename, ".pdf"

    if File.exists?(filename.gsub(".pdf", "-small.mp4"))
      hash[:video] = filename.gsub(".pdf", "-small.mp4")
    elsif File.exists?(filename.gsub(".pdf", "-small.mkv"))
      hash[:video] = filename.gsub(".pdf", "-small.mkv")
    end

    hash[:lesson] = elements[0][1..-1].to_i
    hash[:topic_number] = elements[1]
    hash[:group] = elements[2]
    hash[:topic] = elements[3].gsub("-small", "")
    hash[:extension] = elements[4]

    hash
  end

  template = <<-EOS
  <table class="calendar">
    <thead>
      <tr>
        <th>Date</th>
        <th>Starts at</th>
        <th>Material to prepare</th>
        <th>Content of lesson</th>
        <th>Lesson Recording</th>
      </tr>
    </thead>
    <tbody>
      <% lesson_plan.each do |slot| %>
      <tr>
      <td class="date">
        <%= DateTime.parse(slot[0]).strftime("%a") %><br />
        <%= DateTime.parse(slot[0]).strftime("%d/%b/%Y") %>
      </td>
      <td class="time"><%= DateTime.parse(slot[0]).strftime("%H:%M") %></td>
      <td class="material">
        <%= lesson_to_materials slot[3], materials %>
      </td>
      <td class="content">
        <%= content_to_string slot[4], slot[5] %>
      </td>
      <td class="content">
        <% if slot[6] != "" %>
          <%= zoom_lesson_to_materials slot[6], materials %>
        <% end %>
        <% if slot[7] != "" %>
        <a href="<%= slot[6] %>">Lesson Recording</a>
        <% end %>
      </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  EOS

    require 'csv'
    require 'erb'

    # lesson_plan is a local variable passed in the headers of this source block

    # materials is derived from the pdf files in the "material" directory
    # make sure it is sorted alphabetically
    pdf_files = Dir.glob("./material/*.pdf").sort
    materials = pdf_files.map { |x| filename_to_elements x }

    renderer = ERB.new(template, nil, "-")
    output = renderer.result(binding)

    # for debugging
    # puts pdf_files
    # puts materials

    puts output

#+end_src

#+RESULTS:
#+begin_export html
<table class="calendar">
  <thead>
    <tr>
      <th>Date</th>
      <th>Starts at</th>
      <th>Material to prepare</th>
      <th>Content of lesson</th>
      <th>Lesson Recording</th>
    </tr>
  </thead>
  <tbody>
    
    <tr>
    <td class="date">
      Mon<br />
      14/Sep/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      L1.T11.Introduction.Modeling (<a href="./material/L1.T11.Introduction.Modeling-small.mp4" >VIDEO</a>) (<a href="./material/L1.T11.Introduction.Modeling.pdf" >PDF</a>)
    </td>
    <td class="content">
      Rules and Resources
    </td>
    <td class="content">
      
      
      <a href="">Lesson Recording</a>
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      15/Sep/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      L2.T12.Introduction.Language (<a href="./material/L2.T12.Introduction.Language-small.mp4" >VIDEO</a>) (<a href="./material/L2.T12.Introduction.Language.pdf" >PDF</a>)<br/>
L2.T13.Introduction.LogicalModeling (<a href="./material/L2.T13.Introduction.LogicalModeling-small.mp4" >VIDEO</a>) (<a href="./material/L2.T13.Introduction.LogicalModeling.pdf" >PDF</a>)<br/>
L2.T14.Introduction.WhyLogic (<a href="./material/L2.T14.Introduction.WhyLogic-small.mp4" >VIDEO</a>) (<a href="./material/L2.T14.Introduction.WhyLogic.pdf" >PDF</a>)<br/>
L2.X.1.Introduction.ExerciseOnModels (<a href="./material/L2.X.1.Introduction.ExerciseOnModels-small.mkv" >VIDEO</a>) (<a href="./material/L2.X.1.Introduction.ExerciseOnModels.pdf" >PDF</a>)
    </td>
    <td class="content">
      Students prepare L2
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      21/Sep/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      22/Sep/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      L3.T21.SetTheory.Introduction (<a href="./material/L3.T21.SetTheory.Introduction-small.mp4" >VIDEO</a>) (<a href="./material/L3.T21.SetTheory.Introduction.pdf" >PDF</a>)<br/>
L3.T22.SetTheory.BasicNotions (<a href="./material/L3.T22.SetTheory.BasicNotions-small.mp4" >VIDEO</a>) (<a href="./material/L3.T22.SetTheory.BasicNotions.pdf" >PDF</a>)<br/>
L3.T23.SetTheory.Relations (<a href="./material/L3.T23.SetTheory.Relations-small.mp4" >VIDEO</a>) (<a href="./material/L3.T23.SetTheory.Relations.pdf" >PDF</a>)<br/>
L3.T24.SetTheory.Functions (<a href="./material/L3.T24.SetTheory.Functions-small.mp4" >VIDEO</a>) (<a href="./material/L3.T24.SetTheory.Functions.pdf" >PDF</a>)<br/>
L3.T31.PL.Intuition (<a href="./material/L3.T31.PL.Intuition-small.mp4" >VIDEO</a>) (<a href="./material/L3.T31.PL.Intuition.pdf" >PDF</a>)<br/>
L3.T32.PL.Language (<a href="./material/L3.T32.PL.Language-small.mp4" >VIDEO</a>) (<a href="./material/L3.T32.PL.Language.pdf" >PDF</a>)<br/>
L3.X.1B.Introduction.ExerciseOnModels (VIDEO) (<a href="./material/L3.X.1B.Introduction.ExerciseOnModels.pdf" >PDF</a>)<br/>
L3.X.25A.SetTheory.Exercises (<a href="./material/L3.X.25A.SetTheory.Exercises-small.mkv" >VIDEO</a>) (<a href="./material/L3.X.25A.SetTheory.Exercises.pdf" >PDF</a>)<br/>
L3.X.25B.SetTheory.Exercises (<a href="./material/L3.X.25B.SetTheory.Exercises-small.mp4" >VIDEO</a>) (<a href="./material/L3.X.25B.SetTheory.Exercises.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 1, 2, 3.
    </td>
    <td class="content">
      
      
      <a href="">Lesson Recording</a>
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      28/Sep/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      L4.T33.PL.Satisfiability (<a href="./material/L4.T33.PL.Satisfiability-small.mp4" >VIDEO</a>) (<a href="./material/L4.T33.PL.Satisfiability.pdf" >PDF</a>)<br/>
L4.T34.PL.Validity.Unsat (<a href="./material/L4.T34.PL.Validity.Unsat-small.mp4" >VIDEO</a>) (<a href="./material/L4.T34.PL.Validity.Unsat.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 2, 3, 4.
    </td>
    <td class="content">
      
      
      <a href="">Lesson Recording</a>
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      29/Sep/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      L5.T35.PL.LogCE (<a href="./material/L5.T35.PL.LogCE-small.mp4" >VIDEO</a>) (<a href="./material/L5.T35.PL.LogCE.pdf" >PDF</a>)<br/>
L5.T36.PL.theories (<a href="./material/L5.T36.PL.theories-small.mp4" >VIDEO</a>) (<a href="./material/L5.T36.PL.theories.pdf" >PDF</a>)<br/>
L5.T41.PL.Reasoning.TruthTables.Summary (<a href="./material/L5.T41.PL.Reasoning.TruthTables.Summary-small.mp4" >VIDEO</a>) (<a href="./material/L5.T41.PL.Reasoning.TruthTables.Summary.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 3, 4, 5.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      05/Oct/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      L6.T42.PL.Reasoning.TruthTables.DecisionProblems (<a href="./material/L6.T42.PL.Reasoning.TruthTables.DecisionProblems-small.mp4" >VIDEO</a>) (<a href="./material/L6.T42.PL.Reasoning.TruthTables.DecisionProblems.pdf" >PDF</a>)<br/>
L6.T43.PL.Reasoning.TruthTables.SATCNF (<a href="./material/L6.T43.PL.Reasoning.TruthTables.SATCNF-small.mp4" >VIDEO</a>) (<a href="./material/L6.T43.PL.Reasoning.TruthTables.SATCNF.pdf" >PDF</a>)<br/>
L6.T44.PL.Reasoning.TruthTables.SATDPLL (<a href="./material/L6.T44.PL.Reasoning.TruthTables.SATDPLL-small.mp4" >VIDEO</a>) (<a href="./material/L6.T44.PL.Reasoning.TruthTables.SATDPLL.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 4, 5, 6.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      06/Oct/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      L7.T51.PL.Reasoning.Deduction (<a href="./material/L7.T51.PL.Reasoning.Deduction-small.mp4" >VIDEO</a>) (<a href="./material/L7.T51.PL.Reasoning.Deduction.pdf" >PDF</a>)<br/>
L7.T52.PL.Reasoning.Hilbert.calculus (<a href="./material/L7.T52.PL.Reasoning.Hilbert.calculus-small.mp4" >VIDEO</a>) (<a href="./material/L7.T52.PL.Reasoning.Hilbert.calculus.pdf" >PDF</a>)<br/>
L7.T53.PL.Reasoning.Tableau (<a href="./material/L7.T53.PL.Reasoning.Tableau-small.mp4" >VIDEO</a>) (<a href="./material/L7.T53.PL.Reasoning.Tableau.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 5, 6, 7.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      12/Oct/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      L8.X.1.PL.Exercises (<a href="./material/L8.X.1.PL.Exercises-small.mp4" >VIDEO</a>) (<a href="./material/L8.X.1.PL.Exercises.pdf" >PDF</a>)<br/>
L8.X.25C.SetTheory.Solutions (<a href="./material/L8.X.25C.SetTheory.Solutions-small.mp4" >VIDEO</a>) (<a href="./material/L8.X.25C.SetTheory.Solutions.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 6, 7, 8.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      13/Oct/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      L9.T71.FOL.Intuition (<a href="./material/L9.T71.FOL.Intuition-small.mp4" >VIDEO</a>) (<a href="./material/L9.T71.FOL.Intuition.pdf" >PDF</a>)<br/>
L9.T72.FOL.Language (<a href="./material/L9.T72.FOL.Language-small.mp4" >VIDEO</a>) (<a href="./material/L9.T72.FOL.Language.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 7, 8, 9.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      19/Oct/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      L10.T73.FOL.Interpretation.function (<a href="./material/L10.T73.FOL.Interpretation.function-small.mp4" >VIDEO</a>) (<a href="./material/L10.T73.FOL.Interpretation.function.pdf" >PDF</a>)<br/>
L10.T74.FOL.SAT.wrt.assignment (<a href="./material/L10.T74.FOL.SAT.wrt.assignment-small.mp4" >VIDEO</a>) (<a href="./material/L10.T74.FOL.SAT.wrt.assignment.pdf" >PDF</a>)<br/>
L10.T75.FOL.SAT2LE (<a href="./material/L10.T75.FOL.SAT2LE-small.mp4" >VIDEO</a>) (<a href="./material/L10.T75.FOL.SAT2LE.pdf" >PDF</a>)<br/>
L10.T76.FOL.exercises (<a href="./material/L10.T76.FOL.exercises-small.mp4" >VIDEO</a>) (<a href="./material/L10.T76.FOL.exercises.pdf" >PDF</a>)<br/>
L10.T77.FOL.Finite.Domains (<a href="./material/L10.T77.FOL.Finite.Domains-small.mp4" >VIDEO</a>) (<a href="./material/L10.T77.FOL.Finite.Domains.pdf" >PDF</a>)<br/>
L10.T78.FOL.FOL.wrt.DB (<a href="./material/L10.T78.FOL.FOL.wrt.DB-small.mp4" >VIDEO</a>) (<a href="./material/L10.T78.FOL.FOL.wrt.DB.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 8, 9, 10.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      20/Oct/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      L11.T81.FOL.Reasoning.Hilbert.calculus (<a href="./material/L11.T81.FOL.Reasoning.Hilbert.calculus-small.mp4" >VIDEO</a>) (<a href="./material/L11.T81.FOL.Reasoning.Hilbert.calculus.pdf" >PDF</a>)<br/>
L11.T82.FOL.Reasoning.Tableau (<a href="./material/L11.T82.FOL.Reasoning.Tableau-small.mp4" >VIDEO</a>) (<a href="./material/L11.T82.FOL.Reasoning.Tableau.pdf" >PDF</a>)<br/>
L11.T83.FOL.Reasoning.Tableau.corr.compl (<a href="./material/L11.T83.FOL.Reasoning.Tableau.corr.compl-small.mp4" >VIDEO</a>) (<a href="./material/L11.T83.FOL.Reasoning.Tableau.corr.compl.pdf" >PDF</a>)<br/>
L11.T84.FOL.Reasoning.Tableau.examples (<a href="./material/L11.T84.FOL.Reasoning.Tableau.examples-small.mp4" >VIDEO</a>) (<a href="./material/L11.T84.FOL.Reasoning.Tableau.examples.pdf" >PDF</a>)<br/>
L11.T85.FOL.Reasoning.Tableau.termination (<a href="./material/L11.T85.FOL.Reasoning.Tableau.termination-small.mp4" >VIDEO</a>) (<a href="./material/L11.T85.FOL.Reasoning.Tableau.termination.pdf" >PDF</a>)<br/>
L11.T86.FOL.Reasoning.Tableau.countermodels (<a href="./material/L11.T86.FOL.Reasoning.Tableau.countermodels-small.mp4" >VIDEO</a>) (<a href="./material/L11.T86.FOL.Reasoning.Tableau.countermodels.pdf" >PDF</a>)
    </td>
    <td class="content">
      Q&A about lessons 9, 10, 11.
    </td>
    <td class="content">
      
        L10.Z.Lezione.Frontale (<a href="./material/L10.Z.Lezione.Frontale.pdf" >PDF</a>)<br/>
L10.ZX.Lezione.Frontale (<a href="./material/L10.ZX.Lezione.Frontale.pdf" >PDF</a>)
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      26/Oct/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 10, 11, 12.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      27/Oct/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about mid-term
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      02/Nov/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Mid-term
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      03/Nov/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 11, 12, 13.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      09/Nov/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 12, 13, 14.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      10/Nov/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 13, 14, 15.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      16/Nov/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 14, 15, 16.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      17/Nov/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 15, 16, 17.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      23/Nov/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 16, 17, 18.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      24/Nov/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 17, 18, 19.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      30/Nov/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 18, 19, 20.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      01/Dec/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 19, 20, 21.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      07/Dec/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about lessons 20, 21, 22.
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      08/Dec/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Mon<br />
      14/Dec/2020
    </td>
    <td class="time">14:30</td>
    <td class="material">
      
    </td>
    <td class="content">
      Q&A about final term
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
    <tr>
    <td class="date">
      Tue<br />
      15/Dec/2020
    </td>
    <td class="time">09:00</td>
    <td class="material">
      
    </td>
    <td class="content">
      Final term
    </td>
    <td class="content">
      
      
    </td>
    </tr>
    
  </tbody>
</table>
#+end_export


** Code to build material.csv                                      :noexport:

#+begin_src ruby :exports none :results silent
require 'csv'
files = Dir.glob "/home/adolfo/Slides/*.ppt*"
header = [ ["basename", "topic_no", "subtopic_no", "topic", "subtopic"] ]
content = files.map { |x| m = /L([0-9]+)\.T([0-9]+)\.([^\.]+)\.([^\.]+)/.match(x); [ File.basename(x), m[1].to_i, m[2].to_i, m[3], m[4] ] }
array = header + content

CSV.open("a.csv", "wb") do |csv|
  array.each do |row|
    csv << row
  end
end
#+end_src

** Input Table for Calendar                                        :noexport:

There is no way of specifying that a table cannot be exported.  Hence
I moved the table here, under a heading which is not exported.

#+name: lesson-plan
| date             | week | slot | prepare | content_type     | content              | Pdf? | recording                                                                          |
|------------------+------+------+---------+------------------+----------------------+------+------------------------------------------------------------------------------------|
| 2020-09-14T14:30 |    1 |    1 |       1 | Instructions     | Rules and Resources  |      | https://drive.google.com/file/d/1Fe-tCom7R2Eo_otUfXX5AUP2e_Cxte9-/view?usp=sharing |
| 2020-09-15T09:00 |    1 |    2 |       2 | Prepare          | 2                    |      |                                                                                    |
| 2020-09-21T14:30 |    2 |    3 |         | Lesson suspended |                      |      |                                                                                    |
| 2020-09-22T09:00 |    2 |    4 |       3 | Q&A              | 1, 2, 3              |      | https://drive.google.com/file/d/1rW4NY75IJP3zVFd6TsJrzxeySVLhUV6T/view?usp=sharing |
| 2020-09-28T14:30 |    3 |    5 |       4 | Q&A              | 2, 3, 4              |      | https://drive.google.com/file/d/1-abjdix7esi7t0_Ucz0F2tNplBpVx9B8/view?usp=sharing |
| 2020-09-29T09:00 |    3 |    6 |       5 | Q&A              | 3, 4, 5              |      |                                                                                    |
| 2020-10-05T14:30 |    4 |    7 |       6 | Q&A              | 4, 5, 6              |      |                                                                                    |
| 2020-10-06T09:00 |    4 |    8 |       7 | Q&A              | 5, 6, 7              |      |                                                                                    |
| 2020-10-12T14:30 |    5 |    9 |       8 | Q&A              | 6, 7, 8              |      |                                                                                    |
| 2020-10-13T09:00 |    5 |   10 |       9 | Q&A              | 7, 8, 9              |      |                                                                                    |
| 2020-10-19T14:30 |    6 |   11 |      10 | Q&A              | 8, 9, 10             |      |                                                                                    |
| 2020-10-20T09:00 |    6 |   12 |      11 | Q&A              | 9, 10, 11            |   10 |                                                                                    |
| 2020-10-26T14:30 |    7 |   13 |      12 | Q&A              | 10, 11, 12           |      |                                                                                    |
| 2020-10-27T09:00 |    7 |   14 |         | General Q&A      | Q&A about mid-term   |      |                                                                                    |
| 2020-11-02T14:30 |    8 |   15 |         | Exam             | Mid-term             |      |                                                                                    |
| 2020-11-03T09:00 |    8 |   16 |      13 | Q&A              | 11, 12, 13           |      |                                                                                    |
| 2020-11-09T14:30 |    9 |   17 |      14 | Q&A              | 12, 13, 14           |      |                                                                                    |
| 2020-11-10T09:00 |    9 |   18 |      15 | Q&A              | 13, 14, 15           |      |                                                                                    |
| 2020-11-16T14:30 |   10 |   19 |      16 | Q&A              | 14, 15, 16           |      |                                                                                    |
| 2020-11-17T09:00 |   10 |   20 |      17 | Q&A              | 15, 16, 17           |      |                                                                                    |
| 2020-11-23T14:30 |   11 |   21 |      18 | Q&A              | 16, 17, 18           |      |                                                                                    |
| 2020-11-24T09:00 |   11 |   22 |      19 | Q&A              | 17, 18, 19           |      |                                                                                    |
| 2020-11-30T14:30 |   12 |   23 |      20 | Q&A              | 18, 19, 20           |      |                                                                                    |
| 2020-12-01T09:00 |   12 |   24 |      21 | Q&A              | 19, 20, 21           |      |                                                                                    |
| 2020-12-07T14:30 |   13 |   25 |      22 | Q&A              | 20, 21, 22           |      |                                                                                    |
| 2020-12-08T09:00 |   13 |   26 |         |                  |                      |      |                                                                                    |
| 2020-12-14T14:30 |   14 |   27 |         | General Q&A      | Q&A about final term |      |                                                                                    |
| 2020-12-15T09:00 |   14 |   28 |         | Exam             | Final term           |      |                                                                                    |


** Local Variables                                                 :noexport:

# Local Variables:
# org-confirm-babel-evaluate: nil
# End:
