#+TITLE: Opportunità di Collaborazione nel Gruppo Knowdive@disi
#+AUTHOR: 
#+DATE: <2020-09-12 Sat>

Sono disponibili varie posizioni di 150h nonché posizioni di
studentato interno, da intendersi come prima fase di un progetto di
ricerca e quindi di tesi presso il gruppo stesso. Le attività del
gruppo sono elencate nel sito del gruppo (
http://knowdive.disi.unitn.it/ ), mentre alcune tematiche disponibili
al momento si trovano alla pagina
http://knowdive.disi.unitn.it/work-with-us/. Le attività 150h variano
nel tempo e sono legate ad attività di sviluppo e richiedono quindi
una solida competenza di sviluppo SW. Tutte queste attività possono
anche essere svolte in remoto.

Chiunque sia interessato ad una di queste opportunità mandi email a
mailto:Knowdive-positions@disi.unitn.it, eventualmente anche indicando
le aree o tematiche di interesse. In caso di attività 150h, è
opportuno indicare i linguaggi conosciuti con il corrispondente
livello di competenza, in un valore compreso nell’intervallo è [ 1,5 ]
dove 1= conoscenze di base, 5= conoscenze avanzate.

The applications to the “150 ore” program can be done at the link:

https://www.unitn.it/servizi/224/collaborazioni-studenti-150-ore

Notice that the deadline for applications for the A.Y. 2020-2021 is
**September 30, 2020**.
